<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" Version="8.2.0" />
    <PackageReference Include="FluentValidation" Version="11.12.0" />
    <PackageReference Include="PowerArgs" Version="3.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Formatters\" />
    <Folder Include="Printers\" />
  </ItemGroup>

</Project>